name: Badge Updater

on:
  push:
    branches:
      - Data2
  schedule:
    - cron: "38 9 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: Data2

      - name: Cache and setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Test Badges
        run: |
          cd BadgeUpdater
          RUST_LOG=debug cargo run

      - name: Push to github
        if: ${{ always() }}
        run: |
          git config user.name "badge-updater[bot]"
          git config user.email "badge-updater[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated daily data updating" || echo "No changes to commit"
          git push

      - name: Upload Logs
        uses: actions/upload-artifact@v6
        with:
          name: Logs.txt
          path: BadgeUpdater/badges.temp.txt

      - name: Fail workflow if previous steps failed
        if: ${{ failure() }}
        run: |
          echo "One or more previous steps failed; failing the workflow."
          exit 1
